### ISSUE TITLE
Tufte Layout als Book Template für inwt extension nutzen

### ISSUE THREAD

**Issue by jan-abel-inwt** [INWT/inwt-quarto-template-report#4]
* Versuchen kopie des `tufte` extension zum laufen zu bringen
* den pdf teil aus der`_extension.yml `löschen
* und dann unseren Inhalt nach und nach einfügen bzw. austauschen

**Comment by freimanninwt** [comment]
Ich habe mir das Repo mit `quarto use` auf den Laptop geklont.
Funktioniert hat:
- das Rendern allgemein per `quarto render --to html`
- das Design, es wird übernommen

Nicht funktioniert hat:

- (Montserrat. Vmtl., weil es im vorletzten Patchday aufgespielt wurde, da hatte ich den neuen Laptop nicht)

**Comment by jan-abel-inwt** [comment]
Das Problem mit dem Python Code, liegt daran, dass pro `.qmd` nur ein kernel (`knitr`/`jupyter`) benutzt werden kann. Da der erste Code Chunk in `02-code.qmd` R enthält wird automatisch `knitr` gewählt. Da später dann python code ausgeführt werden soll wird das [`reticulate`](https://rstudio.github.io/reticulate/) benötigt (python interface für R).

Long story short, ich schmeiße es raus ;)

**Comment by jan-abel-inwt** [comment]
Bei mir ist Montserrat installiert. Eigentlich sollte es bei jedem `awx-provision` installiert werden, falls es nicht da ist. Falls das nicht müssten wir das überprüfen.
Magst du das tun, @freimanninwt ?

Die Github Verlinkung ist übrigens super, habe das jetzt noch erweitert. Die Optionen habe ich aber in die `_extension.yml` verschoben. Außerdem gibt
es jetzt einen Footer mit Verlinkungen zur Webseite, linkedin & podcast eingefügt.

Habe noch die readme & die index page angepasst bzw. erweitert.

Danke dir vielmals, damit ist das Template einsatzbereit. Ich habe die Versionsnummer auf 1.0.0 gesetzt. Ab sofort bitte nur noch auf feature 
branches arbeiten.

Schließ gern das issue, nachdem du es gelesen hast.
